AVR Serial Programmer: serial-programmer-at90s2313.h File Reference
serial-programmer-at90s2313.h File Reference
Defines
#define F_CPU 8000000
#define BAUD_RATE 19200
#define FPAGESIZE 32
#define EPAGESIZE 4
#define SCK PB7
#define MISO PB6
#define MOSI PB5
#define RESET PB4
#define PASSTHROUGH PB3
#define LEDPROG PB1
#define LED PB0
Functions
unsigned char BlockLoad (const unsigned int size, const unsigned char mem, uint16_t *address)
void BlockRead (const unsigned int size, const unsigned char mem, uint16_t *address)
Read a block from application memory.
uint8_t writeByte (const uint8_t datum)
Write a Byte to the SPI.
void writeCommand (uint8_t, uint8_t, uint8_t, uint8_t)
Write a four byte Programming command to the SPI.
void pollDelay (const uint8_t shortDelay)
Delay loop for writes.
Define Documentation
#define BAUD_RATE 19200
Definition at line 18 of file serial-programmer-at90s2313.h.
#define EPAGESIZE 4
Definition at line 23 of file serial-programmer-at90s2313.h.
#define F_CPU 8000000
Definition at line 16 of file serial-programmer-at90s2313.h.
#define FPAGESIZE 32
Definition at line 21 of file serial-programmer-at90s2313.h.
#define LED PB0
Definition at line 32 of file serial-programmer-at90s2313.h.
Referenced by main().
#define LEDPROG PB1
Definition at line 31 of file serial-programmer-at90s2313.h.
#define MISO PB6
Definition at line 27 of file serial-programmer-at90s2313.h.
Referenced by writeByte().
#define MOSI PB5
Definition at line 28 of file serial-programmer-at90s2313.h.
Referenced by writeByte().
#define PASSTHROUGH PB3
Definition at line 30 of file serial-programmer-at90s2313.h.
Referenced by main().
#define RESET PB4
Definition at line 29 of file serial-programmer-at90s2313.h.
Referenced by main().
#define SCK PB7
Definition at line 26 of file serial-programmer-at90s2313.h.
Referenced by main(), and writeByte().
Function Documentation
unsigned char BlockLoad (const unsigned int size, const unsigned char mem, uint16_t * address)
void BlockRead (unsigned int size, unsigned char mem, uint16_t * address)
Read a block from application memory.
There is no block read as such in the SPI interface, just do it byte by byte. This code allows the interface to reduce traffic by reading in a single transaction.
Take care that EEPROM addresses are given in bytes, while FLASH addresses are in words.
Note that the low byte is returned first, followed by the high byte. This differs from the 'R' command in which the high byte is returned first.
Parameters:
[in] size,: Size of the buffer in bytes
[in] mem,: Memory type ('E' or 'F')
[in] *address,: pointer to the memory address in bytes (EEPROM) or words (FLASH)
Definition at line 611 of file serial-programmer-at90s2313.c.
References buffer, high, low, lsbAddress, msbAddress, sendchar(), and writeCommand().
Referenced by main().
void pollDelay (const uint8_t shortDelay)
Delay loop for writes.
The target capability for polling the busy status is used to determine if this is to be used or if a fixed delay is needed. The delay is passed in the parameter.
The compiler has a problem with passing a parameter to _delay_ms, and memory usage bloats. So we need some fixed delays. Most likely _delay_us is too general and includes floats.
Note the datasheet labels the flag as RDY, when in fact it states later that it is the inverse, BSY, that is, wait until the flag drops to 0 before proceeding.
Parameters:
[in] shortDelay Is the delay short?: TRUE for FLASH (4.5ms) or FALSE for erase, EEPROM (9ms).
Definition at line 699 of file serial-programmer-at90s2313.c.
References buffer, canCheckBusy, and writeCommand().
Referenced by BlockLoad(), and main().
uint8_t writeByte (const uint8_t datum)
Write a Byte to the SPI.
Issue a write of a single byte on the SPI interface Note that the data is transmitted and received MSB first. Also note that the device is acting as a Master for the SPI bus,so MOSI is output and MISO is input.
Parameters:
[in] datum,: the byte to be written
Returns:
response: a byte read at the same time as the byte was written.
Definition at line 644 of file serial-programmer-at90s2313.c.
References _BV, cbi, inb, MISO, MOSI, outb, sbi, and SCK.
Referenced by writeCommand().
void writeCommand (const uint8_t cmd, const uint8_t parm1, const uint8_t parm2, const uint8_t parm3)
Write a four byte Programming command to the SPI.
Issue a write command on the SPI interface This returns responses which (usually) match the command, one byte delayed. The third byte read from the "start programming" command can be used to verify sync. Other read commands return the read value in the fourth byte.
Parameters:
[in] cmd SPI Programming command
[in] parm1 SPI Programming parameter 1
[in] parm2 SPI Programming parameter 2
[in] parm3 SPI Programming parameter 3
Returns:
The global buffer four bytes with the data returned from the command
Definition at line 677 of file serial-programmer-at90s2313.c.
References buffer, and writeByte().
Referenced by BlockLoad(), BlockRead(), main(), and pollDelay().