AVR Serial Programmer: serial-programmer-test.c File Reference
serial-programmer-test.c File Reference
#include <inttypes.h>
#include <avr/sfr_defs.h>
#include <avr/io.h>
#include <avr/wdt.h>
#include "defines.h"
#include "serial-programmer-at90s2313.h"
#include <util/delay.h>
#include "serial.h"
Defines
#define TRUE 1
#define FALSE 0
#define _BV(bit) (1 << (bit))
#define inb(sfr) _SFR_BYTE(sfr)
#define inw(sfr) _SFR_WORD(sfr)
#define outb(sfr, val) (_SFR_BYTE(sfr) = (val))
#define outw(sfr, val) (_SFR_WORD(sfr) = (val))
#define cbi(sfr, bit) (_SFR_BYTE(sfr) &= ~_BV(bit))
#define sbi(sfr, bit) (_SFR_BYTE(sfr) |= _BV(bit))
#define high(x) ((uint8_t) (x >> 8) & 0xFF)
#define low(x) ((uint8_t) (x & 0xFF))
#define APP_END 0x2000
Functions
int main (void)
unsigned char BlockLoad (uint16_t size, unsigned char mem, uint16_t *address)
Write a block to application memory.
unsigned char BlockRead (unsigned int size, unsigned char mem, uint16_t *address)
Read a block from application memory.
uint8_t writeByte (const uint8_t datum)
Write a Byte to the SPI.
void writeCommand (const uint8_t cmd, const uint8_t parm1, const uint8_t parm2, const uint8_t parm3)
Write a four byte Programming command to the SPI.
Variables
uint16_t address
Serial Programmer Main Program.
unsigned char command
uint8_t result
uint8_t tempInt
uint8_t lsbAddress
uint8_t msbAddress
uint8_t buffer [4]
Define Documentation
#define _BV (bit) (1 << (bit))
Definition at line 56 of file serial-programmer-test.c.
#define APP_END 0x2000
Definition at line 66 of file serial-programmer-test.c.
Referenced by main().
#define cbi (sfr, bit) (_SFR_BYTE(sfr) &= ~_BV(bit))
Definition at line 61 of file serial-programmer-test.c.
#define FALSE 0
Definition at line 54 of file serial-programmer-test.c.
#define high (x) ((uint8_t) (x >> 8) & 0xFF)
Definition at line 63 of file serial-programmer-test.c.
#define inb (sfr) _SFR_BYTE(sfr)
Definition at line 57 of file serial-programmer-test.c.
#define inw (sfr) _SFR_WORD(sfr)
Definition at line 58 of file serial-programmer-test.c.
#define low (x) ((uint8_t) (x & 0xFF))
Definition at line 64 of file serial-programmer-test.c.
#define outb (sfr, val) (_SFR_BYTE(sfr) = (val))
Definition at line 59 of file serial-programmer-test.c.
#define outw (sfr, val) (_SFR_WORD(sfr) = (val))
Definition at line 60 of file serial-programmer-test.c.
#define sbi (sfr, bit) (_SFR_BYTE(sfr) |= _BV(bit))
Definition at line 62 of file serial-programmer-test.c.
#define TRUE 1
Definition at line 53 of file serial-programmer-test.c.
Function Documentation
unsigned char BlockLoad (uint16_t size, unsigned char mem, uint16_t * address)
Write a block to application memory.
The block is firstly written to a temporary buffer to cope with a fast serial communication, then it is written page by page to the AVR internal page buffer, each page followed by a page write. The program allows for blocksizes larger than the internal page buffer, but due to the AT90S2313 SRAM restrictions, it cannot be more than about 64 bytes. The EEPROM internal buffer is typically only 4 bytes, while the FLASH buffer is normally 64. Take care that EEPROM addresses are given in bytes, while FLASH addresses are in words.
We may change this later to not use the block load in either memory type. Due to pagesize variations it is difficult to make this general.
Definition at line 356 of file serial-programmer-test.c.
References buffer, EPAGESIZE, FPAGESIZE, lsbAddress, recchar(), and writeCommand().
unsigned char BlockRead (unsigned int size, unsigned char mem, uint16_t * address)
Read a block from application memory.
There is no block read as such in the SPI interface, just do it byte by byte. Take care that EEPROM addresses are given in bytes, while FLASH addresses are in words. Returns a character representing a status. The block represented by the address is filled with data from memory.
Definition at line 436 of file serial-programmer-test.c.
References buffer, high, low, lsbAddress, msbAddress, sendchar(), and writeCommand().
int main (void)
Definition at line 82 of file serial-programmer-test.c.
References address, APP_END, buffer, cbi, command, high, inb, initbootuart(), low, lsbAddress, msbAddress, outb, recchar(), RESET, result, sbi, SCK, sendchar(), and writeCommand().
uint8_t writeByte (const uint8_t datum)
Write a Byte to the SPI.
Issue a write of a single byte on the SPI interface Note that the data is transmitted and received MSB first. Also note that the device is acting as a Master for the SPI bus,so MOSI is output and MISO is input.
Parameters:
datum,: the byte to be written
Returns:
response: a byte read at the same time as the byte was written.
Definition at line 486 of file serial-programmer-test.c.
References _BV, cbi, inb, MISO, MOSI, outb, sbi, and SCK.
void writeCommand (const uint8_t cmd, const uint8_t parm1, const uint8_t parm2, const uint8_t parm3)
Write a four byte Programming command to the SPI.
Issue a write command on the SPI interface This returns responses which (usually) match the command, one byte delayed. The third byte read from the "start programming" command can be used to verify sync. Other read commands return the read value in the fourth byte.
Parameters:
Four bytes of the SPI Programming command
Returns:
The global buffer four bytes with the data returned from the command
Definition at line 516 of file serial-programmer-test.c.
References buffer, and writeByte().
Variable Documentation
uint16_t address
Serial Programmer Main Program.
This receives a command and interprets it according to the AVRPROG interface.
Definition at line 74 of file serial-programmer-test.c.
uint8_t buffer[4]
Definition at line 80 of file serial-programmer-test.c.
unsigned char command
Definition at line 75 of file serial-programmer-test.c.
uint8_t lsbAddress
Definition at line 78 of file serial-programmer-test.c.
uint8_t msbAddress
Definition at line 79 of file serial-programmer-test.c.
uint8_t result
Definition at line 76 of file serial-programmer-test.c.
Referenced by main().
uint8_t tempInt
Definition at line 77 of file serial-programmer-test.c.