AVR Serial Programmer: serial.c File Reference
serial.c File Reference
#include "defines.h"
Functions
void initbootuart (void)
void sendchar (unsigned char c)
unsigned char recchar (void)
Function Documentation
void initbootuart (void)
Definition at line 22 of file serial.c.
References BAUD_RATE_LOW_REG, BRREG_VALUE, ENABLE_RECEIVER_BIT, ENABLE_TRANSMITTER_BIT, and UART_CONTROL_REG.
Referenced by main().
unsigned char recchar (void)
Definition at line 38 of file serial.c.
References RECEIVE_COMPLETE_BIT, UART_DATA_REG, and UART_STATUS_REG.
Referenced by BlockLoad(), and main().
void sendchar (unsigned char c)
Definition at line 30 of file serial.c.
References TRANSMIT_COMPLETE_BIT, UART_DATA_REG, and UART_STATUS_REG.
Referenced by BlockRead(), and main().