AVR Serial Programmer: serial-programmer-at90s2313.c File Reference
serial-programmer-at90s2313.c File Reference
#include <inttypes.h>
#include <avr/eeprom.h>
#include <avr/sfr_defs.h>
#include <avr/io.h>
#include <avr/wdt.h>
#include "defines.h"
#include "serial-programmer-at90s2313.h"
#include <util/delay.h>
#include "serial.h"
Defines
#define TRUE 1
#define FALSE 0
#define _BV(bit) (1 << (bit))
#define inb(sfr) _SFR_BYTE(sfr)
#define inw(sfr) _SFR_WORD(sfr)
#define outb(sfr, val) (_SFR_BYTE(sfr) = (val))
#define outw(sfr, val) (_SFR_WORD(sfr) = (val))
#define cbi(sfr, bit) (_SFR_BYTE(sfr) &= ~_BV(bit))
#define sbi(sfr, bit) (_SFR_BYTE(sfr) |= _BV(bit))
#define high(x) ((uint8_t) (x >> 8) & 0xFF)
#define low(x) ((uint8_t) (x & 0xFF))
#define NUMPARTS 8
Array of parts and properties.
Functions
int main (void)
unsigned char BlockLoad (uint16_t size, unsigned char mem, uint16_t *address)
Write a block to application memory.
void BlockRead (unsigned int size, unsigned char mem, uint16_t *address)
Read a block from application memory.
uint8_t writeByte (const uint8_t datum)
Write a Byte to the SPI.
void writeCommand (const uint8_t cmd, const uint8_t parm1, const uint8_t parm2, const uint8_t parm3)
Write a four byte Programming command to the SPI.
void pollDelay (const uint8_t shortDelay)
Delay loop for writes.
Variables
uint8_t part [NUMPARTS][6]
uint16_t address
unsigned char command
uint16_t tempInt
uint8_t lsbAddress
uint8_t msbAddress
uint8_t buffer [4]
uint8_t fPageSize
uint8_t ePageSize
uint8_t canCheckBusy
uint8_t lfCapability
uint8_t received
Define Documentation
#define _BV (bit) (1 << (bit))
Definition at line 88 of file serial-programmer-at90s2313.c.
Referenced by writeByte().
#define cbi (sfr, bit) (_SFR_BYTE(sfr) &= ~_BV(bit))
Definition at line 93 of file serial-programmer-at90s2313.c.
Referenced by main(), and writeByte().
#define FALSE 0
Definition at line 86 of file serial-programmer-at90s2313.c.
Referenced by BlockLoad(), and main().
#define high (x) ((uint8_t) (x >> 8) & 0xFF)
Definition at line 95 of file serial-programmer-at90s2313.c.
Referenced by BlockLoad(), BlockRead(), and main().
#define inb (sfr) _SFR_BYTE(sfr)
Definition at line 89 of file serial-programmer-at90s2313.c.
Referenced by main(), and writeByte().
#define inw (sfr) _SFR_WORD(sfr)
Definition at line 90 of file serial-programmer-at90s2313.c.
#define low (x) ((uint8_t) (x & 0xFF))
Definition at line 96 of file serial-programmer-at90s2313.c.
Referenced by BlockLoad(), BlockRead(), and main().
#define NUMPARTS 8
Array of parts and properties.
This lists all the target devices supported by the programmer.
The first signature byte is assumed to be always E1. If not, then we abort programming. Flash and EEPROM page sizes zero means that page writes are not supported. Lock and Fuse support is given by a bitwise quantity. 0 = Lock Read 1 = Fuse Read 2 = High Fuse Read 3 = Extended Fuse Read 4 = Lock Write 5 = Fuse Write 6 = High Fuse Write 7 = Extended Fuse Write
Definition at line 117 of file serial-programmer-at90s2313.c.
Referenced by main().
#define outb (sfr, val) (_SFR_BYTE(sfr) = (val))
Definition at line 91 of file serial-programmer-at90s2313.c.
Referenced by main(), and writeByte().
#define outw (sfr, val) (_SFR_WORD(sfr) = (val))
Definition at line 92 of file serial-programmer-at90s2313.c.
#define sbi (sfr, bit) (_SFR_BYTE(sfr) |= _BV(bit))
Definition at line 94 of file serial-programmer-at90s2313.c.
Referenced by main(), and writeByte().
#define TRUE 1
Definition at line 85 of file serial-programmer-at90s2313.c.
Referenced by BlockLoad(), and main().
Function Documentation
unsigned char BlockLoad (uint16_t size, unsigned char mem, uint16_t * address)
Write a block to application memory.
Block Load can be used to reduce the traffic on the serial link.
The block is read in and is written page by page to the AVR internal page buffer, each page followed by a page write. The program allows for blocksizes larger than the target page buffer. The EEPROM internal buffer is typically only 4 bytes, while the FLASH buffer can be from 16 to 64 words.
Take care that EEPROM addresses are given in bytes, while FLASH addresses are in words.
The code is a bit involved when dealing with non-paged support. We do not use pages at all so pageSize is irrelevant and ends up being -1, which in unsigned arithmetic should be all 1's. However it is used to set the addresses in both paged and non- paged modes, so we may see some side-effects here. It should be worked a bit better but space is running out. In the devices, pages are always used when the memory is above a certain size, so 8-bit addressing should be OK.
Parameters:
[in] size,: Size of the transfer in bytes
[in] mem,: Memory type ('E' or 'F')
[in] *address,: pointer to the memory address in bytes (EEPROM) or words (FLASH)
Returns:
response ('?' or '\r') to return to the PC
Definition at line 536 of file serial-programmer-at90s2313.c.
References ePageSize, FALSE, fPageSize, high, low, lsbAddress, pollDelay(), recchar(), TRUE, and writeCommand().
Referenced by main().
void BlockRead (unsigned int size, unsigned char mem, uint16_t * address)
Read a block from application memory.
There is no block read as such in the SPI interface, just do it byte by byte. This code allows the interface to reduce traffic by reading in a single transaction.
Take care that EEPROM addresses are given in bytes, while FLASH addresses are in words.
Note that the low byte is returned first, followed by the high byte. This differs from the 'R' command in which the high byte is returned first.
Parameters:
[in] size,: Size of the buffer in bytes
[in] mem,: Memory type ('E' or 'F')
[in] *address,: pointer to the memory address in bytes (EEPROM) or words (FLASH)
Definition at line 611 of file serial-programmer-at90s2313.c.
References buffer, high, low, lsbAddress, msbAddress, sendchar(), and writeCommand().
Referenced by main().
int main (void)
Set PORTB as outputs on bits 7,5,4 to set controls, and set high, MISO input on bit 5. Set the Ports PB0-2 as outputs and set high to turn off all LEDs PB0 = programmed LED PB1 = Programming mode LED
'a' Check autoincrement status. This allows a block of data to be uploaded to consecutive addresses without specifying the address each time
'A' Set address. This is stored and incremented for each upload/download. NOTE: Flash addresses are given as word addresses, not byte addresses.
'b' Check block load support. This returns the allowed block size. We will not buffer anything so we will use the FLASH page size to limit the programmer's blocks to those that will fit the target's page. This then avoids the long delay when the page is committed, that may cause incoming data to be lost. This should not be called before the P command is executed, and the target device characteristics obtained. The fPageSize characteristic should be non zero.
'p' Get programmer type. This returns just 'S' for serial.
'S' Return programmer identifier. Always 7 digits. We call it AVRSPRG
'V' Return software version.
't' Return supported device codes. This returns a list of devices that can be programmed. This is only used by AVRPROG so we will not use it, and will work with signature bytes instead.
'x' Set LED.
'y' clear LED.
'T' select device type
'P' Enter programming mode. This starts the programming of the device. Pulse the reset line high while SCK is low. Send the command and ensure that the echoed second byte is correct, otherwise redo. With this we get the device signature and search the table for its characteristics. A timeout is provided in case the device doesn't respond. This will allow fall through to an ultimate error response.
Once we are in programming mode, grab the signature bytes and extract all information about the target device such as its memory sizes, page sizes and capabilities.
'L' Leave programming mode.
'e' Chip erase. This requires several ms. Ensure that the command has finished before acknowledging.
'R' Read program memory
Send high byte, then low byte of flash word. Send each byte from the address specified (note address variable is modified).
'c' Write to program memory page buffer, low byte. NOTE: Always use this command before sending the high byte. It is written to the page but the address is not incremented.
'C' Write to program memory page buffer, high byte. This will cause the word to be written to the page and the address incremented. It is the responsibility of the user to issue a page write command.
'm' Issue Page Write. This writes the target device page buffer to the Flash. The address is that of the page, with the lower bits masked out. This requires several ms. Ensure that the command has finished before acknowledging. We could check for end of memory here but that would require storing the Flash capacity for each device. The calling program will know in any case if it has overstepped.
'D' Write EEPROM memory This writes the byte directly to the EEPROM at the specified address. This requires several ms. Ensure that the command has finished before acknowledging.
'd' Read EEPROM memory
'B' Start block load. The address must have already been set otherwise it will be undefined.
'g' Start block read. The address must have already been set otherwise it will be undefined.
'r' Read lock bits.
'l' Write lockbits.
'F' Read fuse bits.
'f' Write fuse bits.
'N' Read high fuse bits.
'n' Write high fuse bits.
'Q' Read extended fuse bits.
'q' Write extended fuse bits.
's' Return signature bytes. Sent Most Significant Byte first.
'E' Exit bootloader. At this command we enter serial passthrough and don't return from it until a hardware reset occurs. At the same time we should lift the reset from the target. Spin endlessly so we don't interpret serial data, and wait for our own hard reset.
The last command to accept is ESC (synchronization). This is used to abort any command by filling in remaining parameters, after which it is simply ignored. Otherwise, the command is not recognized and a "?" is returned.
Definition at line 143 of file serial-programmer-at90s2313.c.
References address, BlockLoad(), BlockRead(), buffer, canCheckBusy, cbi, command, ePageSize, FALSE, fPageSize, high, inb, initbootuart(), LED, lfCapability, low, lsbAddress, msbAddress, NUMPARTS, outb, part, PASSTHROUGH, pollDelay(), recchar(), received, RESET, sbi, SCK, sendchar(), tempInt, TRUE, and writeCommand().
void pollDelay (const uint8_t shortDelay)
Delay loop for writes.
The target capability for polling the busy status is used to determine if this is to be used or if a fixed delay is needed. The delay is passed in the parameter.
The compiler has a problem with passing a parameter to _delay_ms, and memory usage bloats. So we need some fixed delays. Most likely _delay_us is too general and includes floats.
Note the datasheet labels the flag as RDY, when in fact it states later that it is the inverse, BSY, that is, wait until the flag drops to 0 before proceeding.
Parameters:
[in] shortDelay Is the delay short?: TRUE for FLASH (4.5ms) or FALSE for erase, EEPROM (9ms).
Definition at line 699 of file serial-programmer-at90s2313.c.
References buffer, canCheckBusy, and writeCommand().
Referenced by BlockLoad(), and main().
uint8_t writeByte (const uint8_t datum)
Write a Byte to the SPI.
Issue a write of a single byte on the SPI interface Note that the data is transmitted and received MSB first. Also note that the device is acting as a Master for the SPI bus,so MOSI is output and MISO is input.
Parameters:
[in] datum,: the byte to be written
Returns:
response: a byte read at the same time as the byte was written.
Definition at line 644 of file serial-programmer-at90s2313.c.
References _BV, cbi, inb, MISO, MOSI, outb, sbi, and SCK.
Referenced by writeCommand().
void writeCommand (const uint8_t cmd, const uint8_t parm1, const uint8_t parm2, const uint8_t parm3)
Write a four byte Programming command to the SPI.
Issue a write command on the SPI interface This returns responses which (usually) match the command, one byte delayed. The third byte read from the "start programming" command can be used to verify sync. Other read commands return the read value in the fourth byte.
Parameters:
[in] cmd SPI Programming command
[in] parm1 SPI Programming parameter 1
[in] parm2 SPI Programming parameter 2
[in] parm3 SPI Programming parameter 3
Returns:
The global buffer four bytes with the data returned from the command
Definition at line 677 of file serial-programmer-at90s2313.c.
References buffer, and writeByte().
Referenced by BlockLoad(), BlockRead(), main(), and pollDelay().
Variable Documentation
uint16_t address
Definition at line 131 of file serial-programmer-at90s2313.c.
Referenced by main().
uint8_t buffer[4]
Definition at line 136 of file serial-programmer-at90s2313.c.
Referenced by BlockRead(), main(), pollDelay(), and writeCommand().
uint8_t canCheckBusy
Definition at line 139 of file serial-programmer-at90s2313.c.
Referenced by main(), and pollDelay().
unsigned char command
Definition at line 132 of file serial-programmer-at90s2313.c.
Referenced by main().
uint8_t ePageSize
Definition at line 138 of file serial-programmer-at90s2313.c.
Referenced by BlockLoad(), and main().
uint8_t fPageSize
Definition at line 137 of file serial-programmer-at90s2313.c.
Referenced by BlockLoad(), and main().
uint8_t lfCapability
Definition at line 140 of file serial-programmer-at90s2313.c.
Referenced by main().
uint8_t lsbAddress
Definition at line 134 of file serial-programmer-at90s2313.c.
Referenced by BlockLoad(), BlockRead(), and main().
uint8_t msbAddress
Definition at line 135 of file serial-programmer-at90s2313.c.
Referenced by BlockRead(), and main().
uint8_t part[NUMPARTS][6]
Initial value:
 {
{   0x91,  0x09,   16,    0,   FALSE,  0x77     },
{   0x91,  0x0A,   16,    4,   TRUE,   0xFF     },
{   0x92,  0x05,   32,    4,   TRUE,   0xFF     },
{   0x93,  0x08,   32,    0,   FALSE,  0x77     },
{   0x93,  0x0A,   32,    4,   TRUE,   0xFF     },
{   0x94,  0x03,   64,    4,   TRUE,   0x77     },
{   0x94,  0x06,   64,    4,   TRUE,   0xFF     },
{   0x95,  0x02,   64,    0,   FALSE,  0x77     }
}
Definition at line 118 of file serial-programmer-at90s2313.c.
Referenced by main().
uint8_t received
Definition at line 141 of file serial-programmer-at90s2313.c.
Referenced by main().
uint16_t tempInt
Definition at line 133 of file serial-programmer-at90s2313.c.
Referenced by main().